# use Python 3.10
FROM  python:3.10-alpine

# define timezone
ENV TZ Asia/Shanghai

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# clone code and install requirements
#RUN mkdir /apps && cd /apps \
#    && wget https://github.com/ImYrS/aliyun-auto-signin/archive/refs/heads/main.zip && unzip main.zip -d /apps && rm -rf main.zip \
#    && mv /apps/aliyun-auto-signin-main /apps/aliyun-auto-signin \
#    && cd /apps/aliyun-auto-signin && pip install --no-cache-dir --upgrade -r requirements.txt

RUN mkdir /apps && cd /apps \
    && apk update && apk add git gcc \
    && git clone https://github.com/ImYrS/aliyun-auto-signin.git && cd /apps/aliyun-auto-signin/ \ 
    && pip install --no-cache-dir --upgrade -r requirements.txt \
    && rm -rf /apps/aliyun-auto-signin/.git && apk del --purge git && apk cache clean

# work dir aliyun-auto-signin
WORKDIR /apps/aliyun-auto-signin

# entrypoint
CMD ["python", "app.py"]

